
from abc import ABC, abstractmethod

class StorageAdapter(ABC):
    @abstractmethod
    def list_apps(self): ...
    @abstractmethod
    def get_app(self, slug): ...
    @abstractmethod
    def save_app(self, data): ...
    @abstractmethod
    def delete_app(self, slug): ...
